//! On-disk configuration for Chorus.
//!
//! Lives at `<data_dir>/config.toml`. Written by `chorus setup` after the
//! user picks their data and template directories; read by `chorus run`
//! and `chorus serve` so a user who chose a non-default location once
//! doesn't have to keep passing flags forever.
//!
//! Precedence for any one setting:
//!   1. CLI flag (if the user set it explicitly)
//!   2. This config file
//!   3. Environment variable (where applicable)
//!   4. Hard-coded default
//!
//! `data_dir` is not stored here because the config lives inside it — the
//! directory you're reading from IS the data dir.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

pub const FILE_NAME: &str = "config.toml";

/// Per-runtime overrides. Each runtime gets its own `[<runtime>]` section
/// in `config.toml` so users have a dedicated place to add runtime-specific
/// settings as they emerge. Currently empty; add fields here when needed.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct RuntimeConfig {}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ChorusConfig {
    /// Stable random identifier for this installation. Generated at first
    /// setup, preserved across upgrades. Used by agent-data and telemetry
    /// to attribute records to a specific machine/install.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub machine_id: Option<String>,

    /// Directory holding agent-template markdown files.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub template_dir: Option<String>,

    /// Default agent template id (e.g. `engineering/backend-architect`)
    /// used when `chorus agent create` runs without `--template`. Empty
    /// string = no default; user is prompted or create fails if nothing
    /// else resolves.
    #[serde(default)]
    pub agent_template: String,

    #[serde(default)]
    pub claude: RuntimeConfig,
    #[serde(default)]
    pub codex: RuntimeConfig,
    #[serde(default)]
    pub kimi: RuntimeConfig,
    #[serde(default)]
    pub opencode: RuntimeConfig,
}

impl ChorusConfig {
    pub fn path_for(data_dir: &Path) -> PathBuf {
        data_dir.join(FILE_NAME)
    }

    /// Return the machine id, generating and persisting one if missing.
    /// Fresh installs end up with a UUID v4 on their first call here.
    pub fn ensure_machine_id(&mut self) -> &str {
        if self.machine_id.is_none() {
            self.machine_id = Some(uuid::Uuid::new_v4().to_string());
        }
        self.machine_id.as_deref().unwrap()
    }

    /// Load from `<data_dir>/config.toml`. Returns `Ok(None)` if the file
    /// doesn't exist; `Err` only on I/O or parse failures.
    pub fn load(data_dir: &Path) -> anyhow::Result<Option<Self>> {
        let path = Self::path_for(data_dir);
        if !path.exists() {
            return Ok(None);
        }
        let raw = std::fs::read_to_string(&path)
            .map_err(|e| anyhow::anyhow!("failed to read {}: {e}", path.display()))?;
        let cfg: Self = toml::from_str(&raw)
            .map_err(|e| anyhow::anyhow!("failed to parse {}: {e}", path.display()))?;
        Ok(Some(cfg))
    }

    /// Write atomically (write-to-temp + rename) so an interrupted setup
    /// never leaves a half-written config behind.
    pub fn save(&self, data_dir: &Path) -> anyhow::Result<PathBuf> {
        std::fs::create_dir_all(data_dir)?;
        let path = Self::path_for(data_dir);
        let tmp = path.with_extension("toml.tmp");
        let body = format!(
            "# Chorus config — auto-generated by `chorus setup`.\n\
             # Edit by hand or re-run setup to regenerate.\n\n\
             {}",
            toml::to_string_pretty(self)?
        );
        std::fs::write(&tmp, body)?;
        std::fs::rename(&tmp, &path)?;
        Ok(path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn load_returns_none_when_missing() {
        let tmp = tempfile::tempdir().unwrap();
        assert!(ChorusConfig::load(tmp.path()).unwrap().is_none());
    }

    #[test]
    fn save_then_load_roundtrips_template_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let cfg = ChorusConfig {
            template_dir: Some("/opt/templates".to_string()),
            ..Default::default()
        };
        let written = cfg.save(tmp.path()).unwrap();
        assert!(written.exists());
        let loaded = ChorusConfig::load(tmp.path()).unwrap().unwrap();
        assert_eq!(loaded.template_dir.as_deref(), Some("/opt/templates"));
    }

    #[test]
    fn save_omits_none_fields() {
        let tmp = tempfile::tempdir().unwrap();
        let cfg = ChorusConfig::default();
        cfg.save(tmp.path()).unwrap();
        let raw = std::fs::read_to_string(ChorusConfig::path_for(tmp.path())).unwrap();
        assert!(!raw.contains("template_dir"));
        assert!(!raw.contains("machine_id"));
    }

    #[test]
    fn ensure_machine_id_is_stable() {
        let mut cfg = ChorusConfig::default();
        let first = cfg.ensure_machine_id().to_string();
        let second = cfg.ensure_machine_id().to_string();
        assert_eq!(first, second);
        assert!(uuid::Uuid::parse_str(&first).is_ok());
    }

    #[test]
    fn ensure_machine_id_preserves_existing() {
        let mut cfg = ChorusConfig {
            machine_id: Some("custom-id".to_string()),
            ..Default::default()
        };
        assert_eq!(cfg.ensure_machine_id(), "custom-id");
    }

    #[test]
    fn save_emits_all_runtime_sections() {
        let tmp = tempfile::tempdir().unwrap();
        let cfg = ChorusConfig::default();
        cfg.save(tmp.path()).unwrap();
        let raw = std::fs::read_to_string(ChorusConfig::path_for(tmp.path())).unwrap();
        for runtime in ["claude", "codex", "kimi", "opencode"] {
            assert!(
                raw.contains(&format!("[{runtime}]")),
                "missing [{runtime}] section in:\n{raw}"
            );
        }
    }

    #[test]
    fn roundtrip_preserves_agent_template() {
        let tmp = tempfile::tempdir().unwrap();
        let cfg = ChorusConfig {
            agent_template: "engineering/backend-architect".to_string(),
            ..Default::default()
        };
        cfg.save(tmp.path()).unwrap();
        let loaded = ChorusConfig::load(tmp.path()).unwrap().unwrap();
        assert_eq!(loaded.agent_template, "engineering/backend-architect");
    }
}
